### PR TITLE
Complete revamp

### PR DESCRIPTION
**Pull request by paulbartrum**
Changes:
* Support strikethrough, superscript and inline code spans.
* Support all headings fully.
* Support tables.
* Better support for lists, quotes and code blocks.
* Support backslash escape sequences.
* 10-30x faster parsing than the old code.
* Lots of parsing bugs fixed.

Still to do:
* Fix nested lists (lists within lists).
* Fix quoted lists & code blocks.

### CODE REVIEW

**Comment by QuinnDamerell** [comment]
Wow. This is amazing. I'm going to look it over and then I will pull it in ASAP. 

I am getting this error when trying to use it in Baconit though:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Source file 'C:\Users\quinn\Repos\Baconit\UniversalMarkdown\UniversalMarkdown\Display\MarkdownTable.cs' could not be found.	UniversalMarkdown	C:\Users\quinn\Repos\Baconit\UniversalMarkdown\UniversalMarkdown\CSC

**Comment by QuinnDamerell** [comment]
I also seem to be having trouble opening the Universal markdown solution in VS and building it. Is there something else I have to setup to build it?

Also, just saying this again. This is amazing.

**Comment by QuinnDamerell** [comment]
I mean honestly if you want co-owner (or whatever you call it on GitHub) of this repo I am down for that. You have done amazing work here!

**Comment by QuinnDamerell** [comment]
Didn't mean to close. Sorry.

**Comment by paulbartrum** [comment]
Sorry, missed a file!  It should be there now though.

**Comment by paulbartrum** [comment]
If you want to add me as a collaborator, I would be down with that :-)

**Comment by QuinnDamerell** [comment]
Took a look and it all still looks amazing. Seriously great work, most likely far better than I could have ever done. I will make you a contributor, feel free to do with the project what you see fit. If there are any major refactors or anything you feel need to be done go for it. I will open some issues for things I was thinking about adding for Baconit. :)

**Comment by paulbartrum** [comment]
Thanks for the kind words, and thanks for making Baconit open source!  I've been looking for a project to contribute to for a while; an application that I would actually use on a regular basis.  This is the only project I've found that fits the bill so far.

**Pull request merged**
